### ISSUE TITLE
Theme not recognized by KDE plasma 6

### ISSUE THREAD

**Issue by Vinubrice** [vinceliuice/MacSonoma-kde#10]
The theme is not showing up at the system appearance settings in KDE plasma 6. The bug is not recognized yet.

**Comment by vinceliuice** [comment]
Download the last update here and try again

**Comment by Vinubrice** [comment]
> Download the last update here and try again

OK, thanks 👍🏻, I'll try the last update and close the issue soon

**Comment by Vinubrice** [comment]
> > Download the last update here and try again
> 
> OK, thanks 👍🏻, I'll try the last update and close the issue soon

Well, it didn't work either.....
Try some other way

**Comment by vinceliuice** [comment]
![Screenshot_20240414_015938](https://github.com/vinceliuice/MacSonoma-kde/assets/7604295/134a31b4-865b-48e3-9840-5b0aa7c03dc5)

**Comment by vinceliuice** [comment]
How did you installed this theme ? this issue should be fixed already

**Comment by Vinubrice** [comment]
> How did you installed this theme ? this issue should be fixed already

I installed the theme with the given shell script "install.sh",  I'm using arch linux with KDE plasma 6

**Comment by Vinubrice** [comment]
I tried installing it locally and it works fine, thanks 👍🏻
