### ISSUE TITLE
Theme icons are not used (KDE 6)

### ISSUE THREAD

**Issue by MajorTomDE** [vinceliuice/MacSonoma-kde#14]
Hey, I'm not sure if it's a bug or if I'm making a mistake or have a thinking error
Theme Icons are placed in this folder but are not used

`.local/share/plasma/desktoptheme/MacSonoma-Dark/icons/`

As I understand it, the theme icons should lead and “override” the icons from installed icon-packs (e.g. Breeze, Papirus)?
I remember that it worked with KDE 5.

Same for MacVentura-KDE

**Comment by vinceliuice** [comment]
Plasma 6.0 has stopped using this directory and now only uses icon themes

**Comment by MajorTomDE** [comment]
That's not nice :-(
What do you think? Is it possible that you create an install script that overwrites the relevant icons in the icon theme with those from MacSonoma?

**Comment by vinceliuice** [comment]
I can not add those icons in my icon theme: `[WhiteSur-icon-theme](https://github.com/vinceliuice/WhiteSur-icon-theme)`

**Comment by vinceliuice** [comment]
You can install WhiteSur-icon-theme

**Comment by MajorTomDE** [comment]
But I don't want that ;-) I like the Papirus theme. It's about the icons that should be explicitly replaced by the Sonoma theme. But if that's the intended behavior of KDE, I can close the issue.

**Comment by MajorTomDE** [comment]
But I don't want that :-) I like the Papirus theme. It's about the icons that should be explicitly replaced by the Sonoma theme. But if that's the intended behavior of KDE, I can close the issue.
